### ISSUE TITLE
gentest has a package.json but is not on npm

### ISSUE THREAD

**Issue by eventualbuddha** [graue/gentest#2]
Perhaps `npm publish` this project?

**Comment by graue** [comment]
Hey, thanks for the interest. :) I've deliberately not published gentest yet due to its early state. My thinking is, it should probably have a test suite of its own first (to catch stupid stuff like #1), and I'd like to be successfully using it to test one of my own projects.

With that said, I put it on GitHub early to get feedback. I suppose it doesn't harm much if I put it on npm too with an 0.x version number. I'll think about it and keep this open for the time being.

You can depend on it in the meantime with:

```
"devDependencies": {
  "gentest": "graue/gentest"
}
```

**Comment by graue** [comment]
It's on npm now with a test runner!

```
npm install -g gentest
gentest path/to/tests.js
```
